
dataset: MNIST
num_clients: 10
iid_rate: 0.8             # main-label strategy
malicious_clients: []     # later: [3,7]
epochs: 3
steps_per_client: 200
batch_size: 64
server:
  device: auto            # 'cuda' | 'cpu' | 'auto'
  fifo_size: 10
  lr: 0.01
clients:
  lr_head: 0.01
  lr_tail: 0.01
seed: 1337
