dataset: MNIST
num_clients: 10
iid_rate: 0.8
malicious_clients: []      # later: [3,7]
epochs: 5
steps_per_client: 200
batch_size: 64

server:
  device: auto            # 'cuda' | 'cpu' | 'auto'
  fifo_size: 10
  lr: 0.01

clients:
  lr_head: 0.01
  lr_tail: 0.01

# NEW: SafeSplit defense options
defense:
  enable: true            # toggle defense
  window: 11               # N >= 3 (try 7–11)
  dct_keep_ratio: 0.15    # 0 < r <= 1 (5–15% typical)

seed: 1337
